// vue3-ts-mapboxgl/src/App.vue
<template>
  <div id="mapbox-container" :ref="mapboxContainerRefFn"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue'
import mapboxgl, { Map } from 'mapbox-gl'
import '../node_modules/mapbox-gl/dist/mapbox-gl.css'

export default defineComponent({
  name: 'App',
  setup() {
    let map: Map
    let mapboxContainerRef: HTMLElement
    const mapboxContainerRefFn = (el: any) => {
      mapboxContainerRef = el
    }

    onMounted(() => {
      mapboxgl.accessToken = `your token here`
      map = new Map({
        container: mapboxContainerRef,
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [112.5, 22.3],
        zoom: 7
      })
    })

    return {
      mapboxContainerRefFn
    }
  }
})
</script>

<style>
#mapbox-container {
  width: 100vw;
  height: 100vh;
}
</style>

// react-ts-mapboxgl/src/App.tsx
import React, { useEffect, useRef } from 'react'
import mapboxgl, { Map } from 'mapbox-gl'
import '../node_modules/mapbox-gl/dist/mapbox-gl.css'
import './App.css'

function App() {
  const mapDivRef = useRef<HTMLDivElement>(null)
  let map: Map

  mapboxgl.accessToken = `your token here`

  useEffect(() => {
    map = new Map({
      container: mapDivRef.current as HTMLElement,
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [112.5, 22.3],
      zoom: 7
    })
  }, [])

  return <div id="mapbox-container" ref={mapDivRef}></div>
}

export default App
