// svelte-ts-cesium/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Viewer } from "cesium";
  import "../node_modules/cesium/Source/Widgets/widgets.css";

  let viewerDiv: HTMLDivElement;
  let viewer: Viewer;

  onMount(() => {
    viewer = new Viewer(viewerDiv);
  });
</script>

<main>
  <div id="viewer" bind:this={viewerDiv} />
</main>

<style>
  #viewer {
    width: 100vw;
    height: 100vh;
  }
</style>

// react-ts-cesium181/src/App.tsx
import React, { useEffect, useRef } from 'react'
import { Viewer } from 'cesium'
import '../node_modules/cesium/Source/Widgets/widgets.css'
import './App.css'

let viewer: Viewer
function App() {
  const cesiumRef = useRef<HTMLDivElement>(null)
  
  useEffect(() => {
    viewer = new Viewer(cesiumRef.current as HTMLDivElement)
  })

  return <div id="cesium-container" ref={cesiumRef}></div>
}

export default App
