// svelte-ts-leaflet/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Map, map, tileLayer } from "leaflet";

  import "../node_modules/leaflet/dist/leaflet.css";

  let lfViewDiv: HTMLElement;
  let lfMap: Map;

  onMount(() => {
    lfMap = map(lfViewDiv).setView([22.3, 112.5], 7); // 纬度, 经度
    tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png").addTo(
      lfMap
    );
  });
</script>

<main>
  <div id="lf-view" bind:this={lfViewDiv} />
</main>

<style>
  #lf-view {
    width: 100vw;
    height: 100vh;
  }
</style>

// react-ts-leaflet/src/App.tsx
import React, { useRef, useEffect } from 'react'
import { map, tileLayer } from 'leaflet'
import '../node_modules/leaflet/dist/leaflet.css'
import './App.css'

function App() {
  const lfRef = useRef<HTMLDivElement>(null)
  let lfMap
  useEffect(() => {
    lfMap = map(lfRef.current as HTMLElement).setView([22.3, 112.5], 7) // 纬度, 经度
    tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(lfMap)
  }, [])
  return <div id="lf-container" ref={lfRef}></div>
}

export default App
