// svelte-js-openglobus/src/App.svelte
<script>
  import { onMount } from "svelte";
  import { Globe, layer, terrain } from "@openglobus/og";

  import "../node_modules/@openglobus/og/css/og.css";
  let globus;

  onMount(() => {
    globus = new Globe({
      target: "globusDiv",
      name: "earth",
      terrain: new terrain.GlobusTerrain(),
      layers: [
        new layer.XYZ("OpenStreetMap", {
          isBaseLayer: true,
          url: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          visibility: true,
        }),
      ],
      autoActivated: true,
      viewExtent: [5.56707, 45.15679, 5.88834, 45.2226],
    });
  });
</script>

<main>
  <div id="globusDiv" />
</main>

<style>
  #globusDiv {
    width: 100vw;
    height: 100vh;
  }
</style>

// vue3-js-openglobus/src/App.vue
<template>
  <div id="globus-container"></div>
</template>

<script setup>
import { onMounted } from 'vue'
import { Globe, layer, terrain } from '@openglobus/og'

import '../node_modules/@openglobus/og/css/og.css'

let globus
onMounted(() => {
  globus = new Globe({
    target: 'globus-container',
    name: 'earth',
    terrain: new terrain.GlobusTerrain(),
    layers: [
      new layer.XYZ("OpenStreetMap", {
        isBaseLayer: true,
        url: '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        visibility: true
      })
    ],
    autoActivated: true,
    viewExtent: [5.56707, 45.15679, 5.88834, 45.22260]
  })
})
</script>

<style>
#globus-container {
  width: 100vw;
  height: 100vh;
}
</style>
